services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - chat-network
    restart: always

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_DB_URI=${MONGO_DB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=3000
      - NODE_ENV=production
    networks:
      - chat-network
    restart: always

networks:
  chat-network:
    driver: bridge